remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum", "sunrise"

title: Paco's Atomic Cloud
description: A simple blog to dump something atomic and fun for the cloud thingy I have done/am doing/will do.
author: 
  name: 'Paco Luo'
  email: paco.luo@gmail.com
  twitter_username: brahmasky
  github_username:  brahmasky
show_excerpts: true # set to false to remove excerpts on the homepage
logo: /assets/img/wukong.png

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
theme: jekyll-theme-minimal

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true