# remote_theme: pages-themes/architect@v0.2.0
theme: jekyll-theme-minimal
title: Paco's Atomic Cloud
description: A simple blog to dump something atomic and fun for the cloud thingy I have done/am doing/will do.
author: 
  name: 'Paco Luo'
  email: paco.luo@gmail.com
  twitter_username: brahmasky
  github_username:  brahmasky
show_excerpts: true # set to false to remove excerpts on the homepage
logo: /assets/img/wukong.png

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
theme: jekyll-theme-minimal